title: Simple Questionnaires
url: "https://fergusferrier.github.io"
baseurl: "/simple-questionnaires"
kramdown:
  input: Kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - DEVELOPING.md
